let sb=null,currentUser=null,currentAdmin=null,storeSettings={},adminProducts=[]; const $=id=>document.getElementById(id); const isConfigured=()=>window.RIDAA_SUPABASE&&!window.RIDAA_SUPABASE.url.includes('YOUR_PROJECT')&&!window.RIDAA_SUPABASE.anonKey.includes('YOUR_');
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function msg(m,ok=false){$('authMsg').textContent=m;$('authMsg').style.color=ok?'#16835b':'#a22538'}
async function init(){if(!isConfigured()||!window.supabase){$('setupNotice').classList.remove('hidden');msg('اربط Supabase أولًا حسب ملف README_ADMIN_SETUP.md');return;} sb=window.supabase.createClient(window.RIDAA_SUPABASE.url,window.RIDAA_SUPABASE.anonKey); const {data:{session}}=await sb.auth.getSession(); if(session) await enterAdmin(session.user); bind();}
function bind(){
 $('loginForm').addEventListener('submit',login);$('signupForm').addEventListener('submit',signup);$('showSignup').onclick=()=>{$('loginForm').classList.add('hidden');$('showSignup').classList.add('hidden');$('signupForm').classList.remove('hidden')};$('showLogin').onclick=()=>{$('signupForm').classList.add('hidden');$('loginForm').classList.remove('hidden');$('showSignup').classList.remove('hidden')};$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
 document.querySelectorAll('.sidebar nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view,b)); $('addProductBtn').onclick=()=>openProductEditor();$('closeProductDialog').onclick=$('cancelProduct').onclick=()=> $('productDialog').close();$('productForm').addEventListener('submit',saveProduct);$('settingsForm').addEventListener('submit',saveSettings);$('contentForm').addEventListener('submit',saveSettings);$('mediaUpload').addEventListener('change',uploadMedia);$('inviteForm').addEventListener('submit',inviteAdmin);
}
async function login(e){e.preventDefault();msg('جارٍ تسجيل الدخول...',true);const {data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)return msg(error.message);await enterAdmin(data.user);}
async function signup(e){e.preventDefault();msg('جارٍ إنشاء الحساب...',true);const {data,error}=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value});if(error)return msg(error.message);if(data.user){msg('تم إنشاء الحساب. إذا كان تأكيد البريد مفعّلًا، افتح رسالة التأكيد ثم سجّل الدخول.',true);}}
async function enterAdmin(user){const {data,error}=await sb.from('admins').select('*').eq('user_id',user.id).eq('active',true).maybeSingle(); if(error||!data){await sb.auth.signOut();return msg('هذا الحساب ليس لديه صلاحية إدارة. يجب أن يكون البريد ضمن دعوات المدراء.');} currentUser=user;currentAdmin=data;$('authScreen').classList.add('hidden');$('adminApp').classList.remove('hidden');$('welcomeText').textContent=`مرحبًا، ${data.email}`;$('roleBadge').textContent=data.role==='super_admin'?'Super Admin':'Admin';if(data.role!=='super_admin')$('adminsNav').classList.add('hidden'); await refreshAll();}
function switchView(v,btn){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('view-'+v).classList.add('active-view');document.querySelectorAll('.sidebar nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const names={overview:'لوحة التحكم',products:'المنتجات',settings:'معلومات المتجر',content:'محتوى الصفحة',media:'الصور والوسائط',admins:'المدراء والصلاحيات'};$('viewTitle').textContent=names[v];if(v==='media')loadMedia();if(v==='admins')loadAdmins();}
async function refreshAll(){await Promise.all([loadProducts(),loadSettings()]);if(currentAdmin.role==='super_admin')await loadAdmins();await loadMedia();$('statProducts').textContent=adminProducts.length;}
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('sort_order',{ascending:true});if(error)return toast(error.message);adminProducts=data||[];$('productsTable').innerHTML=adminProducts.map(p=>`<tr><td><img class="thumb" src="${p.image_url||''}"></td><td>${p.name}</td><td>${p.label||p.category}</td><td>${p.price} د.م</td><td><span class="pill ${p.active?'on':'off'}">${p.active?'ظاهر':'مخفي'}</span></td><td><div class="actions"><button onclick="editProduct(${p.id})">تعديل</button><button class="danger" onclick="deleteProduct(${p.id})">حذف</button></div></td></tr>`).join('');$('statProducts').textContent=adminProducts.length;}
function openProductEditor(p={}){const f=$('productForm');f.reset();f.elements.id.value=p.id||'';f.elements.name.value=p.name||'';f.elements.category.value=p.category||'women';f.elements.label.value=p.label||'نسائي';f.elements.price.value=p.price||'';f.elements.old_price.value=p.old_price||'';f.elements.badge.value=p.badge||'';f.elements.sort_order.value=p.sort_order||0;f.elements.is_new.checked=!!p.is_new;f.elements.active.checked=p.active!==false;f.elements.image_url.value=p.image_url||'';f.elements.description.value=p.description||'';$('productDialogTitle').textContent=p.id?'تعديل المنتج':'إضافة منتج';$('productDialog').showModal();}
window.editProduct=id=>openProductEditor(adminProducts.find(p=>Number(p.id)===Number(id)));window.deleteProduct=async id=>{if(!confirm('حذف هذا المنتج نهائيًا؟'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)return toast(error.message);toast('تم حذف المنتج');loadProducts();};
async function saveProduct(e){e.preventDefault();const f=e.target;let image=f.elements.image_url.value.trim();const file=$('productImageFile').files[0];if(file)image=await uploadOne(file);const payload={name:f.elements.name.value.trim(),category:f.elements.category.value,label:f.elements.label.value.trim(),price:Number(f.elements.price.value),old_price:f.elements.old_price.value?Number(f.elements.old_price.value):null,badge:f.elements.badge.value.trim()||null,sort_order:Number(f.elements.sort_order.value)||0,is_new:f.elements.is_new.checked,active:f.elements.active.checked,image_url:image,description:f.elements.description.value.trim()};let error;if(f.elements.id.value){({error}=await sb.from('products').update(payload).eq('id',f.elements.id.value));}else{({error}=await sb.from('products').insert(payload));}if(error)return toast(error.message);$('productDialog').close();toast('تم حفظ المنتج');loadProducts();}
async function uploadOne(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await sb.storage.from('product-images').upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from('product-images').getPublicUrl(path).data.publicUrl;}
async function loadSettings(){const {data,error}=await sb.from('store_settings').select('data').eq('id',1).maybeSingle();if(error)return toast(error.message);storeSettings=data?.data||{};[$('settingsForm'),$('contentForm')].forEach(form=>{[...form.elements].forEach(el=>{if(el.name&&Object.prototype.hasOwnProperty.call(storeSettings,el.name))el.value=storeSettings[el.name]??'';});});}
async function saveSettings(e){e.preventDefault();const patch={};[...e.target.elements].forEach(el=>{if(el.name)patch[el.name]=el.value});const merged={...storeSettings,...patch};const {error}=await sb.from('store_settings').upsert({id:1,data:merged,updated_at:new Date().toISOString()});if(error)return toast(error.message);storeSettings=merged;toast('تم حفظ التعديلات');}
async function loadMedia(){const {data,error}=await sb.storage.from('product-images').list('',{limit:200,sortBy:{column:'created_at',order:'desc'}});if(error){$('mediaGrid').innerHTML='<p>لم يتم إنشاء مخزن الصور بعد.</p>';return;}const files=(data||[]).filter(x=>!x.name.startsWith('.'));$('statMedia').textContent=files.length;$('mediaGrid').innerHTML=files.map(f=>{const url=sb.storage.from('product-images').getPublicUrl(f.name).data.publicUrl;return `<div class="media-card" title="انقر على الصورة لنسخ الرابط"><img src="${url}" onclick="copyMediaUrl('${encodeURIComponent(url)}')"><button onclick="deleteMedia('${encodeURIComponent(f.name)}')">×</button></div>`}).join('')||'<p>لا توجد صور مرفوعة بعد.</p>';}
async function uploadMedia(e){for(const file of [...e.target.files]){try{await uploadOne(file)}catch(err){toast(err.message);break}}e.target.value='';toast('تم رفع الصور');loadMedia();}
window.copyMediaUrl=async enc=>{const url=decodeURIComponent(enc);await navigator.clipboard.writeText(url);toast('تم نسخ رابط الصورة');};
window.deleteMedia=async enc=>{const name=decodeURIComponent(enc);if(!confirm('حذف الصورة من المخزن؟'))return;const {error}=await sb.storage.from('product-images').remove([name]);if(error)return toast(error.message);toast('تم حذف الصورة');loadMedia();};
async function loadAdmins(){if(currentAdmin?.role!=='super_admin')return;const [{data:a},{data:i}]=await Promise.all([sb.from('admins').select('*').order('created_at'),sb.from('admin_invites').select('*').order('created_at',{ascending:false})]);$('statAdmins').textContent=(a||[]).length;$('adminsList').innerHTML=(a||[]).map(x=>`<div class="list-row"><div><b>${x.email}</b><br><small>${x.role}</small></div>${x.user_id===currentUser.id?'<span>أنت</span>':`<button onclick="removeAdmin('${x.user_id}')">حذف</button>`}</div>`).join('');$('invitesList').innerHTML=(i||[]).map(x=>`<div class="list-row"><div><b>${x.email}</b><br><small>${x.role}</small></div><button onclick="removeInvite('${encodeURIComponent(x.email)}')">إلغاء الدعوة</button></div>`).join('')||'<p>لا توجد دعوات معلقة.</p>';}
async function inviteAdmin(e){e.preventDefault();if(currentAdmin.role!=='super_admin')return;const payload={email:$('inviteEmail').value.trim().toLowerCase(),role:$('inviteRole').value,invited_by:currentUser.id};const {error}=await sb.from('admin_invites').upsert(payload);if(error)return toast(error.message);$('inviteEmail').value='';toast('تمت إضافة دعوة المدير');loadAdmins();}
window.removeInvite=async enc=>{await sb.from('admin_invites').delete().eq('email',decodeURIComponent(enc));loadAdmins()};window.removeAdmin=async id=>{if(!confirm('إزالة صلاحية هذا المدير؟'))return;await sb.from('admins').delete().eq('user_id',id);loadAdmins()};
init();
