-- RIDAA Store secure admin backend (Supabase)
-- Run this file once in Supabase > SQL Editor.
-- IMPORTANT: replace the first-admin email below if needed.

create extension if not exists citext;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email citext unique not null,
  role text not null default 'admin' check (role in ('admin','super_admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_invites (
  email citext primary key,
  role text not null default 'admin' check (role in ('admin','super_admin')),
  invited_by uuid null references public.admins(user_id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'women',
  label text not null default 'نسائي',
  price numeric(12,2) not null default 0,
  old_price numeric(12,2),
  badge text,
  is_new boolean not null default false,
  image_url text,
  description text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id integer primary key check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admins a where a.user_id = uid and a.active = true); $$;

create or replace function public.is_super_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admins a where a.user_id = uid and a.active = true and a.role = 'super_admin'); $$;

create or replace function public.claim_admin_invite()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if exists(select 1 from public.admin_invites i where lower(i.email::text)=lower(new.email)) then
    insert into public.admins(user_id,email,role)
    select new.id,new.email,i.role from public.admin_invites i where lower(i.email::text)=lower(new.email)
    on conflict (user_id) do update set email=excluded.email, role=excluded.role, active=true;
    delete from public.admin_invites where lower(email::text)=lower(new.email);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_ridaa on auth.users;
create trigger on_auth_user_created_ridaa after insert on auth.users for each row execute procedure public.claim_admin_invite();

alter table public.admins enable row level security;
alter table public.admin_invites enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (active = true or public.is_admin());
drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products for insert with check (public.is_admin());
drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products for delete using (public.is_admin());

drop policy if exists "public read store settings" on public.store_settings;
create policy "public read store settings" on public.store_settings for select using (true);
drop policy if exists "admins insert settings" on public.store_settings;
create policy "admins insert settings" on public.store_settings for insert with check (public.is_admin());
drop policy if exists "admins update settings" on public.store_settings;
create policy "admins update settings" on public.store_settings for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read admins" on public.admins;
create policy "admins read admins" on public.admins for select using (public.is_admin());
drop policy if exists "super admins manage admins insert" on public.admins;
create policy "super admins manage admins insert" on public.admins for insert with check (public.is_super_admin());
drop policy if exists "super admins manage admins update" on public.admins;
create policy "super admins manage admins update" on public.admins for update using (public.is_super_admin()) with check (public.is_super_admin());
drop policy if exists "super admins manage admins delete" on public.admins;
create policy "super admins manage admins delete" on public.admins for delete using (public.is_super_admin());

drop policy if exists "super admins read invites" on public.admin_invites;
create policy "super admins read invites" on public.admin_invites for select using (public.is_super_admin());
drop policy if exists "super admins insert invites" on public.admin_invites;
create policy "super admins insert invites" on public.admin_invites for insert with check (public.is_super_admin());
drop policy if exists "super admins update invites" on public.admin_invites;
create policy "super admins update invites" on public.admin_invites for update using (public.is_super_admin()) with check (public.is_super_admin());
drop policy if exists "super admins delete invites" on public.admin_invites;
create policy "super admins delete invites" on public.admin_invites for delete using (public.is_super_admin());

insert into storage.buckets (id,name,public) values ('product-images','product-images',true)
on conflict (id) do update set public=true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select using (bucket_id='product-images');
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update to authenticated using (bucket_id='product-images' and public.is_admin()) with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and public.is_admin());

insert into public.store_settings(id,data) values (1, jsonb_build_object(
  'store_name','RIDAA Store','tagline','رداء يليق بكِ','phone','+212 600 000 000','whatsapp','212600000000','email','hello@ridaastore.com','address','المغرب',
  'instagram','#','facebook','#','tiktok','#','topbar_one','شحن مجاني للطلبات فوق 1000 د.م','topbar_two','توصيل داخل المغرب خلال 3–7 أيام',
  'hero_eyebrow','مجموعة RIDAA الجديدة','hero_title','تسوّقي بكل أناقة','hero_accent','بتفاصيل تصنع الفرق','hero_subtitle','تصاميم محتشمة، أنثوية وعصرية مختارة بعناية لتمنحك حضورًا مميزًا.',
  'stat_designs','+500','stat_years','12','stat_rating','4.9','category_intro','فساتين وعبايات بتصاميم محتشمة تناسب اليوم والمناسبة.',
  'custom_title','صمّمي إطلالتك الخاصة','custom_text','أرسلي لنا فكرتك أو صورة مرجعية، وحددي اللون والخامة والتفاصيل. نتواصل معك لتأكيد القياسات قبل التنفيذ.',
  'story_title','نصمم رداءً يعكس أناقتك','story_text','في RIDAA نهتم بالقصة والخامة والقصّة قبل كل شيء. هدفنا أن تصلك قطعة جميلة، مريحة، ومصنوعة بتفاصيل تشبهك.',
  'footer_description','متجر أزياء محتشمة وتصميم وتفصيل حسب الطلب.',
  'logo_light_url','assets/logo-light.svg','hero_image_url','assets/products/model-set/dusty-rose.jpg','custom_image_url','assets/products/model-set/sky-blue.jpg',
  'category_women_image_url','assets/products/model-set/sage.jpg','category_girls_image_url','assets/products/model-set/mint.jpg','category_custom_image_url','assets/products/model-set/fuchsia.jpg',
  'story_image_1','assets/products/model-set/fuchsia.jpg','story_image_2','assets/products/model-set/lavender.jpg','story_image_3','assets/products/model-set/mint.jpg',
  'women_category_title','فساتين وعبايات راقية','girls_category_title','إطلالات ناعمة للصغيرات','custom_category_title','قطعة مصنوعة لأجلك',
  'testimonial_1_name','سارة','testimonial_1_text','التفصيل دقيق والخامة جميلة جدًا، والتواصل كان سريعًا وواضحًا.',
  'testimonial_2_name','مريم','testimonial_2_text','التغليف أنيق والمقاس جاء مضبوطًا. سأكرر الطلب بالتأكيد.',
  'testimonial_3_name','هدى','testimonial_3_text','أحببت تنسيق الألوان والتفاصيل، والموقع سهل جدًا في الطلب.'
)) on conflict (id) do nothing;


-- API privileges; RLS policies above still decide which rows/actions are allowed.
grant usage on schema public to anon, authenticated;
grant select on public.products, public.store_settings to anon;
grant select, insert, update, delete on public.products, public.store_settings, public.admins, public.admin_invites to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- First admin invitation. This email was prefilled from the account shown while deploying.
-- Change it here if you want a different first administrator.
insert into public.admin_invites(email,role) values ('Almshagbaabdallah@gmail.com','super_admin')
on conflict (email) do update set role='super_admin';

-- If that user already exists in Supabase Auth before you run this SQL, promote it immediately too.
insert into public.admins(user_id,email,role)
select id,email,'super_admin' from auth.users where lower(email)=lower('Almshagbaabdallah@gmail.com')
on conflict (user_id) do update set role='super_admin',active=true;

-- Optional initial catalog. Only inserts if products is empty.
insert into public.products(name,category,label,price,old_price,badge,is_new,image_url,description,active,sort_order)
select * from (values
 ('فستان وردي كلاسيكي','women','نسائي',385,445,'الأكثر طلبًا',true,'assets/products/model-set/dusty-rose.jpg','فستان طويل بقصة أنيقة وحزام جانبي.',true,1),
 ('فستان لافندر مزهر','women','نسائي',399,469,'جديد',true,'assets/products/model-set/lavender.jpg','فستان لافندر ناعم بلمسات زهرية.',true,2),
 ('عباية زيتي أنيقة','women','نسائي',429,489,'مميز',true,'assets/products/model-set/sage.jpg','إطلالة زيتية هادئة وأنيقة.',true,3),
 ('فستان سماوي راقٍ','women','نسائي',369,429,'حصري',true,'assets/products/model-set/sky-blue.jpg','فستان سماوي بقصة محتشمة.',true,4),
 ('فستان فوشيا للمناسبات','women','نسائي',459,519,'مميز',true,'assets/products/model-set/fuchsia.jpg','فستان فوشيا للمناسبات.',true,5),
 ('فستان نعناعي ناعم','girls','بناتي',249,299,'بناتي',true,'assets/products/model-set/mint.jpg','لون نعناعي هادئ وتصميم ناعم.',true,6)
) as v(name,category,label,price,old_price,badge,is_new,image_url,description,active,sort_order)
where not exists(select 1 from public.products);
